workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter pub run flutter_launcher_icons
      - flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
